---
- name: Install PostgreSQL
  become: yes
  block:
    - name: Install PostgreSQL on Ubuntu
      ansible.builtin.apt:
        name: postgresql
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install PostgreSQL on CentOS
      ansible.builtin.yum:
        name: postgresql-server
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Start PostgreSQL service
      ansible.builtin.systemd:
        name: postgresql
        state: started
